### ISSUE TITLE
OpenComputers Events aren't fired

### ISSUE THREAD

**Issue by Setadokalo** [AlmuraDev/SGCraft#10]
I was recently trying to make a system that automatically sent a response through when the gate opened, but tests showed that the events mentioned in the documentation weren't ever fired. Tests on an older version of my pack showed that the events did get fired in 1.10.2.

**Comment by Dockter** [comment]
Can you give me anything to go by with this?  I don't personally use OpenComputers so I need some context to the problem.

**Comment by Setadokalo** [comment]
I'm not really sure what you mean. Essentially though, OpenComputers has an interface system that lets blocks be controlled by the computers, and part of that is that they send events. (For easy testing, you can just read all events with a loop like `while true do print(require('event').pull()) end`) In the original mod, there were events fired when the stargate did things, such as an event for chevrons locking, an event for dialing the gate, closing and opening the iris, etc. They're all visible in the [documentation page](http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/SGCraft/Doc/ComputerCraft.html).

**Comment by opencma** [comment]
The events seem to be firing. Make sure the OpenComputers stargate interface is directly below the stargate.

SGCraft: 1.14.2-mc1.12.2
OpenComputers: 1.7.2.67
Forge: 14.23.2.2611

**Comment by Setadokalo** [comment]
![2018-03-15_13 34 47](https://user-images.githubusercontent.com/29683020/37484159-c05d6c0e-2855-11e8-8778-92353a9c4af8.png)
Opened a stargate connection while running an event print loop, never caught a single event from the stargate. And yes, the interface is in the correct spot with a cable running to the computer.
SGCraft / OpenComputers: Same version as above
Forge: 2605.

**Comment by Dockter** [comment]
@DarkEnchanter1 I dont use OC at all, have you made any progress towards this issue?

**Comment by Dockter** [comment]
I've verified that the events are firing correctly.
