### ISSUE TITLE
Structure addon flags have no effect

### ISSUE THREAD

**Issue by LemADEC** [AlmuraDev/SGCraft#105]
As of SGCraft-2.0.1, the flags to disable specific structure addons during world generation have no effect whatsoever except for the pyramid one.
Namely, `igloo_addon`, `jungle_addon` and `swamp_addon` shouldn't be in the configuration file.

**Comment by Dockter** [comment]
Hm, will investigate this.

**Comment by Dockter** [comment]
Fixed in upcoming build 2.0.2+
