### ISSUE TITLE
[Suggestion] Move pegasus gate dial speed to config

### ISSUE THREAD

**Issue by gt22** [AlmuraDev/SGCraft#106]
Currently, pegasus gate dial speed is hardcoded:

https://github.com/AlmuraDev/SGCraft/blob/a2fb3f32f17761fc45fad1fdaf6d325f32792e5e/src/mod/gcewing/sg/tileentity/SGBaseTE.java#L2767

I think it should be moved to config, similarly to milky way gate speed.

**Comment by Dockter** [comment]
I certainly can add this to the next build.

**Comment by Dockter** [comment]
Wait, this is just the default value it sets when changing the gate types, you can set the value to anything you want....
