### ISSUE TITLE
Event Horizon isn't destroying blocks

### ISSUE THREAD

**Issue by Sarous** [AlmuraDev/SGCraft#110]
Blocks within the gate ring itself are not being destroyed.

SGCraft 2.0.2

**Comment by Dockter** [comment]
If they are indestructable they wont be anymore, I added a config option for this.

**Comment by Dockter** [comment]
Bedrock for example.

**Comment by Sarous** [comment]
Regular ol dirt. And its a standing gate.

**Comment by Dockter** [comment]
..... wtf.

**Comment by craft90** [comment]
Had the same issue with sandstone aswell as stone. It didn't even unform when I placed blocks within in ring either. It just dialed as normal even with transist damage on.

**Comment by Dockter** [comment]
Did you enable this value in the config?

**Comment by Dockter** [comment]
Finally was able to replicate this, fix will be included in 2.0.3+
