### ISSUE TITLE
Stargates doesn't deal enough damage

### ISSUE THREAD

**Issue by BDevGW** [AlmuraDev/SGCraft#112]
When I wear a Draconic Evolution armor the event horizon doesn't even hurt me.
Could you increase it's damage to ensure that anything killable WILL die when they are at the wrong place at the wrong time?

**Comment by Dockter** [comment]
What type of gate did you build and what do you have the transient damage in the config set to?

**Comment by BDevGW** [comment]
Yes the damage is enabled and it was a normal gate, not a pegasus gate.
All damage is taken by my armor and more testing showd that a protection IV enchanted endstell armor from EnderIO can save your life too.

**Comment by Dockter** [comment]
Actually this is a valid bug.  The intended result is suppose to be death.

**Comment by Dockter** [comment]
internal note:  SGBaseTE:  final static double transientDamageRate = 50;

**Comment by BDevGW** [comment]
Just for your information, a draconic armor can have a few thousands of shield.
Also as far as I can see the damage can be lowered by armor and protection enchantment. Some mods add an armor which can lower the damage by 100% 
I hope the vortex will also be deadly in such armors ^^

Also whatever you do I hope you will also fix this in a 1.12.2 release since thats the current version where me and my friends are playing :)

**Comment by Dockter** [comment]
I'm going to make the transientDamageRate configurable in the master config file.

**Comment by Dockter** [comment]
This is fixed in build 2.0.3
