### ISSUE TITLE
[Suggestion] Add Tollan stargate as an upgrade like the Pegasus upgrade

### ISSUE THREAD

**Issue by Deliphin** [AlmuraDev/SGCraft#113]
The Tollan stargate is a very sleek design, and I think it should be a sidegrade to the Pegasus gate.

If you want it to have different specs, you could possibly make it like a stealth stargate. Silent, but as slow as the Milky Way stargate. I'm thinking this because the chevrons don't look like they can actually move and engage.

![Tollan Stargate](https://vignette.wikia.nocookie.net/stargate/images/8/86/New_Tollan_Stargate.jpg/revision/latest?cb=20100402035411)

**Comment by Dockter** [comment]
Good idea however at the moment I lack the ability to do new models for SGCraft.

**Comment by Dockter** [comment]
I'd love to but I would need someone to code the new 3d render in GL code and then provide the textures.
