### ISSUE TITLE
Cannot break blocks

### ISSUE THREAD

**Issue by ExDomino** [AlmuraDev/SGCraft#115]
Stargate blocks and Dhd cannot be picked up with any pickaxe, even dimond ones. Blocks are always lost.

**Comment by ExDomino** [comment]
I found that is a config in the option. But there is a problem: a misplaced block cannot be moved.
I suggest you two modifications:

1) Silktouch can break blocks.
2) You can harvest the DHD and a ring block without silktouch if the stargate is not completed.
3) A non harvestable block should take as long as without tool to harvest it.

For the second suggestion, I mean incomplete stargates ring blocks, for example a misplaced one, can be picked up, but when the stargate is complete, only silktouch can break them in order to retrieve the block. For the third suggestion, it is to inform the player that their will not get the block.

**Comment by Dockter** [comment]
I think I have a better idea.  Only mark the blocks as un-harvestable AFTER the gate is initially created.

**Comment by Dockter** [comment]
OK, so that idea wont work because blocks are singletons.  So, what I think I may do is allow people to turn these values to true but add an additional check to prevent the player to break a gate if its assembled.

**Comment by ExDomino** [comment]
Yes, except if you have silktouch.

**Comment by Dockter** [comment]
Nah, I'm working on a better idea.  My goal of this is to prevent users from harvesting structure generated gates.

**Comment by Ezoteric** [comment]
you could also do it like Actually Additions does its decoration machines in the village house, you can use them but once you break them they are gone :)

**Comment by Dockter** [comment]
This feature I talked about above was implemented.
