### ISSUE TITLE
Keep drones running when going through dimensions via stargates

### ISSUE THREAD

**Issue by Deliphin** [AlmuraDev/SGCraft#116]
I just realized this might be on Stargate Network's side and not OpenComputers. It's probably not, but I don't really know.

Original issue: https://github.com/MightyPirates/OpenComputers/issues/3161

**Current Behavior**
If a drone goes through a stargate that leads to another dimension, it immediately stops and sits right at the event horizon (the blue wavy stuff).
I have tried using a drone with a chunkloader upgrade, and that doesn't change the behavior.
`OpenComputers-MC1.12.2-1.7.4.153`
`SGCraft-2.0.2`

![Drone sitting dead at the event horizon of a stargate](https://user-images.githubusercontent.com/14265753/66091076-9de08600-e55c-11e9-8a45-9199220c5389.png)

**Desired Behavior**
If a drone goes through a stargate, it should continue on with whatever it was doing- likely resetting its 0,0 placement point relative to the original stargate, to the new destination stargate, in the new dimension.

I want this behavior so I can use a drone like a MALP. Before I go through a stargate and risk running into an iris or something else dangerous, I would like to send a drone through, and have it report back what it discovers. But none of this is possible if it immediately shuts down upon teleportation.

If you had the drone reboot once it's on the other side, that would also be acceptable, and might not require modifying OpenComputers.

**Comment by Dockter** [comment]
Not knowing how the entity works, I know for a fact that a Minecraft does respect this pre/post stargate event.  If you push a cart through it exits the event horizon at the same direction relative to the gate and the same velocity.  It could be that the mod you're using for the drone has its own entity type that isnt a built-in entity thus its skipping my entity reset velocity / direction calls.

**Comment by Dockter** [comment]
No response.  I have never used / created a drone so I would need that information.  Can't expect me to learn a new mod just because its not working as intended with SGCraft.
