### ISSUE TITLE
[Suggestion] shader portal animation

### ISSUE THREAD

**Issue by ben-mkiv** [AlmuraDev/SGCraft#122]
Hello,

i've recently started to make a sg-craft inspired portal for one of my mods, which uses Shaders for the Portal animation. Today i've noticed that SG-Craft was ported to 1.12.2...

https://www.youtube.com/watch?v=ss40Gu-x-qA

I would implement it as optional feature and make a PR if you are interested in that.

It comes with some flaws caused by minecraft render engine, thats why i would suggest to make it an optional feature (using a TESR and so the rendering isn't depth sorted, which can conflict with other TESRs (they get invisible behind the portal animation)

https://www.shadertoy.com/view/4tsXRH

![](https://i.imgur.com/p2jP4Pr.png)

**Comment by Dockter** [comment]
Yes, I'm interested!

**Comment by Dockter** [comment]
No reply, closing ticket.

**Comment by ben-mkiv** [comment]
sorry for the late reply, it's still somewhere on my todo list, however it currently has low priority.

I'll make an PR when its done
