### ISSUE TITLE
[Suggestion] Add config option to restrict only OPs to see gates' addresses

### ISSUE THREAD

**Issue by Deliphin** [AlmuraDev/SGCraft#123]
Basically, if you're a regular user and right click a stargate, you get nothing except that facade thing for the bottom blocks. If you're an OP, you get what regular users get currently.

This would be useful to me for my exploration themed modpack, for me and some friends.

Basically, each of us spawn on our own planet. I'll be throwing addresses in a ton of places, but I won't be allowed to look at the addresses after that.

When we actually start playing, we have to find addresses, even the addresses just to go to each others' worlds. That's the whole purpose of this- we can't see our own address, so we have to be careful traveling.

Also, it would be nice if you could have another config to make it so you could still read the address if you have The One Probe, following the idea of hovering over with the proper tool to get extra info.

**Comment by Dockter** [comment]
Frankly I love this idea.  Let me play around with a couple of options.

**Comment by Dockter** [comment]
I have added this ability in 2.0.3.
