### ISSUE TITLE
Make Flan's Vehicles pass through the stargate

### ISSUE THREAD

**Issue by Deliphin** [AlmuraDev/SGCraft#124]
```
Flan's Mod-1.12.2-5.5.2
SGCraft-2.0.2
```

Current behaviour:  
If you drive through a stargate in a Flans vehicle (any flans vehicle, I tested several), you will hear the woosh, and you will briefly experience a bit of teleport bugginess, but you will be put back right where you were- passing through the stargate as if it was never active.

I've drive land and flying vehicles. However the only flying vehicle I tried, the basic biplane, made the stargate blow up.

I'd like to be able to drive flans vehicles through the stargate and have them come out of the other side.

![2019-11-18_21 04 28](https://user-images.githubusercontent.com/14265753/69107288-39fc1900-0a47-11ea-90eb-da426eb147e9.png)

**Comment by gaiaweylyn** [comment]
Not sure on the gate transit, but I do know the cause of the blowing up part. Flying vehicles in flans have a block breaking mechanic which I assume is meant to emulate crash damage. It's unlikely to affect whether or not the vehicles pass through the gates, but it may be possible to turn off the terrain damage mechanic in the configs for that mod to at least prevent Stargate explosions.

Definitely worth contacting the Flans dev about this as well, to see if they ave any input on the cause.

**Comment by Deliphin** [comment]
There already is one open that I've commented on: https://github.com/FlansMods/FlansMod/issues/859
No response from Flans' dev though. And it's an old issue too.

I posted here in hopes maybe it was something someone here could make a workaround for, or contact Flans' dev directly about.

**Comment by Dockter** [comment]
@Deliphin please join this: https://discord.gg/MV6cx8F

I would like to talk to you about this issue.

**Comment by Dockter** [comment]
I found this mod to be extremely developer unfriendly.  It crashes with sponge because its not checking for NPE's in their code, their GUI's crash with errors, can't spawn a vehicle.  I don't have time to test something that requires me to learn a new mod.
