### ISSUE TITLE
zpm not interacting with conduits or TE energy ducts

### ISSUE THREAD

**Issue by Mikecolle** [AlmuraDev/SGCraft#125]
tried both have not tried ic2 cart yet but with no way to use the ic2 power as forge energy it defeated the purpose of using the zpm for power.

**Comment by Dockter** [comment]
I have just tested again, the ZPM Console > to RF Energy Cell, worked fine.

![image](https://user-images.githubusercontent.com/1034770/72212689-3795c880-34a6-11ea-92f8-93c333c4b4a3.png)
