### ISSUE TITLE
way to recharge the zpm via industrial craft cart or zpm interface

### ISSUE THREAD

**Issue by Mikecolle** [AlmuraDev/SGCraft#127]
i was wondering if theres a way to add a zpm charger probably the same model as the interface just retextured. i want to do an atlantis themed base with zpm power but i need a way to recharge them once they are spent.

i am willing to do the texture if you can do the coding

**Comment by gaiaweylyn** [comment]
I feel like ZPMs should be a very limited/special thing as they are in universe. 

They can’t be recharged either, at least not with the knowledge of modern humans as per known canon.

**Comment by Mikecolle** [comment]
or a very expensive way to fabricate them as the replicators did.

**Comment by gaiaweylyn** [comment]
Perhaps. And yes, granted, the Lanteans obviously had the knowledge and technological capability to manufacture them. So if a mechanic like this were to be theoretically added, I'd definitely opt for the second option for canon's sake.. And I'd certainly insist on this having a big kill switch in the configs to disable it if someone doesn't want it enabled on a server.

**Comment by Mikecolle** [comment]
also i saw another mod that has the ring transporters for 1.12 but dont like the models if someone would be able to add the code i could take a crack at the models


Mike

**Comment by Dockter** [comment]
What are you going to use for the models?

**Comment by Dockter** [comment]
No response from user.
