### ISSUE TITLE
ZPM oddities and explosions

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [AlmuraDev/SGCraft#128]
I have come across 2 different ZPM modules in the chests located by the stargates.
One glows like its enchanted.
![2019-11-27_19 56 31](https://user-images.githubusercontent.com/10451525/69768794-0f4d4700-1150-11ea-8c5a-70fc90d018c1.png)
One does not.
![2019-11-27_19 56 34](https://user-images.githubusercontent.com/10451525/69768799-14aa9180-1150-11ea-9eb9-5f53bd8314f8.png)

When I use the non glowing one in a ZPM Console, it delivers RF power and drains like a battery.
If I put a glowing one in, this happens....
![2019-11-27_19 58 27](https://user-images.githubusercontent.com/10451525/69768850-4e7b9800-1150-11ea-9584-e291d723ff7c.png)

Is there some use case for each or is this intended behavior?

Also the ZPM Cart causes ANYTHING IC2 Classic to explode violently.
IC2 Classic uses the original E-Net with Packets.  
For it to cause a PESU to explode, it has to be emitting packets larger than 32768 EU/T.
Just wondering if that is also intended behavior?

Please let me know.
Id like to use the ZPM Modules, but explosions are bad for my health.

Thank You.

**Comment by Dockter** [comment]
The glow affect ZPM's are tainted.  Pulling power from them is indeed bad for your health.  This is intended.

**Comment by MachiavelliSeraphim** [comment]
I was wondering about that.
Thanks.

Also, whats the indended output from the ZPM cart supposed to be?
