### ISSUE TITLE
Unable to Fast dial with PDD

### ISSUE THREAD

**Issue by citpo** [AlmuraDev/SGCraft#130]
Hi 

I'm unable to use the PDD while having the GDO in my off-hand. 
When right-clicking with the PDD in my main-hand the interface of the GDO opens.

Isn't fast-dial intended to work with the  PDD?

Using verison: 2.0.2
with dependency: malisiscore-1.12.2-6.5.1.jar

**Comment by Dockter** [comment]
No, fast dial was intended to be enabled/disabled using the configurator.  Its a base setting on each gate now.

Im not sure I can fix the above scenario though because Mojang calls both hand interact events each time right-click is used.

**Comment by citpo** [comment]
Thanks for response. 
Found the setting on the base. 
Closing the issue.
