### ISSUE TITLE
[Bug] zpm console performance issues

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [AlmuraDev/SGCraft#131]
mod v2.0.2
when the zpm console is placed in singleplayer everything is fine but if i place it in a server it freezes the client for a second every few seconds until the block is broken.

not my server so i dont have the logs, i'll ask for them.

**Comment by Dockter** [comment]
Damn, I seen this issue once before.  I'll investigate.

**Comment by Dockter** [comment]
I've investigated this and found no issues indev, in single player or server/client.  I need something more to go on or I can't assist.

**Comment by C4PTRAMPAGE** [comment]
[latest.log](https://github.com/AlmuraDev/SGCraft/files/4050512/latest.log)
as you can see it looks like it was a minimap mod i use trying to calculate what the block should look like on it, so yeah not your problem to fix.
