### ISSUE TITLE
[Question] 2.0.3 unavailable 

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [AlmuraDev/SGCraft#132]
the mods curseforge page has a changelog for version 2.0.3 but the latest on the files page is 2.0.2, was 2.0.3 taken down for some reason?

**Comment by Dockter** [comment]
It has not posted yet, I started putting my notes about 2.0.3 up on that page.  I was about to release it but I am not yet satisfied with my model for the ZPM Hub.
