### ISSUE TITLE
[Bug ]Gate shuts down mid dial

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [AlmuraDev/SGCraft#133]
the gate sometimes shuts itself off while dialing, at first i thought it was the dhd script i was running in the opencomputers... computer, but after initiating the connection then shutting the computer off the gate still shut itself down, after some testing it looks like the computer dial usually fails but dialing from the pdd always works... possibly an issue with the oc computer interface? if it matters the gate i tried to connect with was in the same dimension and a good distance away (+18000 blocks) it happened on a server but this has occurred in singleplayer before, i didn't report it before because i thought it was the dhd program. again not my server so no logs yet.

**Comment by KamaroTheN7** [comment]
I have that same problem, gates works perfectly fine with DHD, but for some reason this happens when I use dialing program on OpenComputers, this same program works great on original SGCraft.

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/ghei36>

________________________________

**Comment by Dockter** [comment]
Its possible that the server forced the chunk to unload on the destination gate.  If this is the case then some other mod is messing with the forge chunk loading ticket system.  Without further details I can't investigate this properly.
