### ISSUE TITLE
[Mod Conflict] zpm console lag

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [AlmuraDev/SGCraft#135]
first off i dont even know if i can reopen an issue i created much less how so sorry about opening a new one but i found out why this https://github.com/AlmuraDev/SGCraft/issues/131 is happening. as you can see here [latest.log](https://github.com/AlmuraDev/SGCraft/files/4050541/latest.log) it looks like the minimap mod i use freezes the game when it tries to figure out what the zpm console looks like on the map. i've been unable to contact the dev of that mod, is there anything you can do to fix it on your end?

**Comment by Tsoccerguy3** [comment]
That might be a issue with the liteloader your using to load Voxel minimap , mixins are wrong version . This is not the reason . There is a memory leak in one of the methods used by the console . There are lots of conflicts with many mods. Place a console and a software loop is created and it uses up all the memory

**Comment by Dockter** [comment]
If your claiming memory leak then I need profiler logs.

**Comment by C4PTRAMPAGE** [comment]
> That might be a issue with the liteloader your using to load Voxel minimap , mixins are wrong version . This is not the reason . There is a memory leak in one of the methods used by the console . There are lots of conflicts with many mods. Place a console and a software loop is created and it uses up all the memory

i'm not using liteloader i have the forge version of voxelmap and as for a memory leak i have no idea all i know about it is that it only lags if i place the zpm console on top of a solid block when voxelmap is installed

**Comment by C4PTRAMPAGE** [comment]
@Dockter uhh... is this the right log? 
[profile-results-2020-01-14_23.14.16.txt](https://github.com/AlmuraDev/SGCraft/files/4063189/profile-results-2020-01-14_23.14.16.txt)

**Comment by C4PTRAMPAGE** [comment]
waiting for response...

**Comment by Dockter** [comment]
No, that is not a memory profiler log.  That only shows ticks.  Profiler logs come from a program such as YourKit.

**Comment by C4PTRAMPAGE** [comment]
yeah so yourkit has about 5000000 settings for recording as many log types.

**Comment by C4PTRAMPAGE** [comment]
i dont know anything about java and your telling me about me a tool that was clearly made for someone who knows what their doing, do you see the problem here?

**Comment by Tsoccerguy3** [comment]
Try this , press F3 and in the upper right corner write down memory used and percentage or take a screen shot . Then place the zpm  console and record the the memory used and percentage . https://minecraft.gamepedia.com/Debug_screen . this will be a good indicator if something is wrong . The correct terminology is to say there is a conflict . I myself have experienced multiple conflicts . I'm still looking into it .

**Comment by C4PTRAMPAGE** [comment]
either your being sarcastic or you didn't properly read through the thread before posting

**Comment by Dockter** [comment]
Question; how did you come to the conclusion that the ZPM Console is the start of the issue?

You're error log indicates that your computer ran out of memory.  The note you made indicates that the map was having issues figuring out the color for the block type on the map.  Where did that information come from?  The value MapColor is set when the block is created off its Material type which is properly set.

**Comment by C4PTRAMPAGE** [comment]
when i have the minimap on screen or i open the fullscreen map the game lags when i dont its fine so its just conjecture but because theres no lag when it isnt being drawn on the map it makes sense, look anything i tell about what i think is causing this is going to be guesswork.

**Comment by Dockter** [comment]
I would ask you to give this a try again with build 2.0.4 - beta 5 or later.  Please re-open if issue is still happening.
