### ISSUE TITLE
[Enhancement] event horizon should emit light

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [AlmuraDev/SGCraft#137]
in the show the stargate's wormhole emits a good amount of light, i mean you cant make the event horizon itself do that (at least if the mod/minecraft work the way i think they do however i dont know much about java) anyway what about making the base block emit light when the wormhole is there

**Comment by Dockter** [comment]
I'd love to do this unfortunately I haven't figure out a way to do so after a bunch of attempts.

**Comment by Dockter** [comment]
Added to the to-do list.
