### ISSUE TITLE
[suggestion] dim blacklist

### ISSUE THREAD

**Issue by superon** [AlmuraDev/SGCraft#139]
if possible it would be super to implement either or both of these into next or otherwise some future release as a config option:
1. prevent dialling to gate/s in specified dim/s from another dim
(this way one would be able to only have outgoing gates)
2. prevent placing/spawning gates in specified dim
(to completely remove possibility of dialling to or from specified dim/s)

**Comment by Dockter** [comment]
I'll add this to my to-do list.
