### ISSUE TITLE
ZPM Console interacts with the wrong side of FE Blocks

### ISSUE THREAD

**Issue by mallrat208** [AlmuraDev/SGCraft#141]
So this is a bit of a weird one...

I've been playing around with using this in a modpack and ran into some shenanigans trying to get the ZPM Console to power FE accepting blocks. Using Immersive Engineering Capacitors,  you have to enable power acceptance on the opposite side of the block you would expect. So if a ZPM Console has a HV Capacitor to the East, you need the East side of the Capacitor to accept power, not the WEST as you'd expect since that's the side actually in contact with the ZPM Console. 

https://github.com/AlmuraDev/SGCraft/blob/a335ea6eabef5c089f1dda7fe026e1165bcb6af1/src/mod/gcewing/sg/features/zpm/console/ZpmConsoleTE.java#L325-L331

references to `side` on lines 328 to 331 should probably refer to `side.getOpposite()` 

This might also explain one or two of the other issues people have had with the Console seemingly not working at random despite working in testing. A block that doesn't care what side the energy is coming from would never run into this issue, only something setup to be sided would.

**Comment by Dockter** [comment]
I'm curious if you've tested that change by chance?

**Comment by Dockter** [comment]
I have looked at this again; give this a try:
http://solder.almuramc.com/downloads/SGCraft-2.0.4-beta-2.jar

**Comment by Dockter** [comment]
Confirmed fixed in version 2.0.4 beta 3 or newer.
