### ISSUE TITLE
[Suggestion] Backward updates?

### ISSUE THREAD

**Issue by Nyabloody** [AlmuraDev/SGCraft#142]
I would love to see the changes you made on this mod but for 1.7.10 ? Pwease :(

//rant on
I'm one of the many that hates the newer minecraft versions past 1.8+ for a lot of reasons, like the combat system and such...

And I still don't get why people update their mods to those dumb newer versions. Also it means a lot of rework to get things ported to newer versions right? While it would be easier to just stick to one good version forever and keep updating mods on it. But meh...
//rant off

**Comment by Dockter** [comment]
I've got to be honest, I would like to attempt to do this at some point, though I ton of stuff changed between versions.
