### ISSUE TITLE
Servers aren't able to read the config file

### ISSUE THREAD

**Issue by uncoveredkhan09** [AlmuraDev/SGCraft#144]
I've been playing with my friends on a (McProhosting) server and I was the first one to build a gate, i put it down and decided i didnt like where it was, so i tried to break it....nothing. it would use up durability but wouldnt actually break the gate :P and i have it set so people can break gates. 

They also didnt spawn in structures when i set it to 100 for every kind but we ran into several and none of them had gates, tokras, or ZPMs

**Comment by dallenwilson** [comment]
Can you fire up a local world with the same mods, make the same changes to your SGCraft config file, and see if they are honoured? I've been doing quite a bit of work with the worldgen code lately and had no problem with config file options being read and used. Your problem could be a client/server thing, or a mod conflict. Lets find out which.

**Comment by uncoveredkhan09** [comment]
I actually just took the config file from a local world I was already playing on with the mods and it worked fine there, started living out of a desert temple then.

**Comment by Ezoteric** [comment]
We had the same problem but that was because "canPlayerBreakGate=true" was by default on false....

this setting to true fixed the problem for us

**Comment by Dockter** [comment]
I agree with @Ezoteric .  Please check that.  Remember, each gate is unique, so if you had that setting wrong either break the gate and replace it OR use the Configurator to disable/enable the value.
