### ISSUE TITLE
Mixins crash

### ISSUE THREAD

**Issue by AechtRob** [AlmuraDev/SGCraft#147]
The mod crashes at startup in conflict with the latest Vanilla Fix, which has some Mixins updates in it. (MC 1.12.2)

**Comment by Dockter** [comment]
Can't help without a log.

**Comment by AechtRob** [comment]
Apologies.... here is a sample log.
[latest.log](https://github.com/AlmuraDev/SGCraft/files/4432250/latest.log)

**Comment by Dockter** [comment]
Last person who reported this was using an out of date version of VanillaFix.

**Comment by AechtRob** [comment]
This is the latest VanillaFix-1.0.10-150.jar

**Comment by Dockter** [comment]
The next build I am completely removing Mixin and the fact that its a CoreMod.  Wait until 2.0.4.  I'll put a build up of it shortly for you to try.

**Comment by Dockter** [comment]
http://solder.almuramc.com/downloads/sgcraft/SGCraft-2.0.4.jar

Try this.

**Comment by AechtRob** [comment]
Well... it doesn't crash with VanillaFix any more, which is good. But I've not tested beyond that - is there a changelog to check or things to watch out for which may be impacted?

**Comment by Dockter** [comment]
I will be available shortly.
