### ISSUE TITLE
Use of illegal characters in MS Windows names cause game to crash

### ISSUE THREAD

**Issue by Tsoccerguy3** [AlmuraDev/SGCraft#15]
SGCraft/src/mod/gcewing/sg/SGDimensionMap.java 

    public static SGDimensionMap get() {
        World world = BaseUtils.getWorldForDimension(0);
return BaseUtils.getWorldData(world, SGDimensionMap.class, "sgcraft:dimension_map");

use of the ":" character in a name on windows is not allowed , change "sgcraft:dimension_map" to
"sgcraft-dimension_map"

**Comment by Dockter** [comment]
Fixed in 1.15.1.  Builds will be available here:  https://ore.spongepowered.org/Dockter/SGCraft  once I post them.
