### ISSUE TITLE
Configurator can't save

### ISSUE THREAD

**Issue by Shadowninja397** [AlmuraDev/SGCraft#150]
Hello,

So when using the configurator if I try to use it to change options on the gates I cannot actually click save as there is no where for me to do so. Here is a picture showing what I mean. 
![Capture](https://user-images.githubusercontent.com/53382736/79033745-ff1d8d80-7b6d-11ea-9d7e-87f2b762e1af.PNG)

**Comment by Dockter** [comment]
You need to change your GUI scaling option, you can't see several things.
