### ISSUE TITLE
Naquadah ore generates in all dimensions, not just in the Overworld

### ISSUE THREAD

**Issue by Ainsley4Ever** [AlmuraDev/SGCraft#153]
I'm using version 2.0.3 of your mod, and I've seen naquadah ore generate in the Nether, in the End, and in modded dimensions such as the Betweenlands or the Erebus. Is it possible to restrict ore generation to one specific dimension (the Overworld in this case)? If not, would it be possible to add a dimension whitelist/blacklist for naquadah ore generation?

**Comment by Dockter** [comment]
Ability to configure which dimensions to have naquadah generate has been added by @Sykes368
