### ISSUE TITLE
Immersive Engineering connectors and batteries can't extract energy from ZPM consoles

### ISSUE THREAD

**Issue by Ainsley4Ever** [AlmuraDev/SGCraft#154]
I'm using version 2.0.3 of SG Network, and I've noticed that it's impossible to collect energy from a ZPM console using Immersive Engineering's wire connectors or batteries. I remember being able to do this with Thermal Expansion's fluxducts and IC2's cables, so Immersive Engineering's wires should be able to do the same.

**Comment by dallenwilson** [comment]
For what it's worth, I have successfully used the ZPM console to directly power several different IE machines. I haven't tried using it with IE capacitors (batteries) or wire connectors, though.

**Comment by Ainsley4Ever** [comment]
You're right, I did some testing and the console can directly power IE machines. But it doesn't work with capacitors and connectors, which is kind of a bummer since you can't use a ZPM to power your entire base.

**Comment by Ainsley4Ever** [comment]
Just noticed this issue which better explains the problem. The ZPM console does interact with the block (which means I was wrong), but it does so with the opposite side to the one it should be interacting with.

https://github.com/AlmuraDev/SGCraft/issues/141

**Comment by Dockter** [comment]
Please give this a try:  http://solder.almuramc.com/downloads/SGCraft-2.0.4-beta-3.jar

**Comment by Ainsley4Ever** [comment]
It seems to work correctly now. Well done, and thanks for the help.
