### ISSUE TITLE
Port mod for new versions of Minecraft

### ISSUE THREAD

**Issue by ilaore** [AlmuraDev/SGCraft#169]
Will this mod be ported to new versions of Minecraft? For example, 1.14.4, 1.15.2 and newer versions that will be released.

**Comment by Dockter** [comment]
As stated in previous ticket, the next likely jump will be to 1.16.2 due to the fact that Mojang changed world generation.  IC2, buildcraft, etc haven't even released version for the builds you specified.

**Comment by ilaore** [comment]
> Как говорилось в предыдущем билете, следующий вероятный скачок будет до 1.16.2 из-за того, что Mojang изменил мировое поколение. IC2, buildcraft и т. д. Даже не выпустили версию для указанных вами сборок.

Thanks)
