### ISSUE TITLE
ZPMs can go into negative energy

### ISSUE THREAD

**Issue by Bysokar** [AlmuraDev/SGCraft#171]
As shown here:

https://github.com/AlmuraDev/SGCraft/blob/master/src/mod/gcewing/sg/features/ic2/zpm/modulehub/ZpmHubTE.java#L137
https://github.com/AlmuraDev/SGCraft/blob/master/src/mod/gcewing/sg/features/ic2/zpm/interfacecart/ZpmInterfaceCartTE.java#L128

ZPMs can go into negative energy, and whilst they will immediately be found depleted after dropping below zero it would be nice to fix this one up :)

Should just require a tweak to return supply, not amount.

**Comment by Dockter** [comment]
I agree with this.  Fix incoming.
