### ISSUE TITLE
Crash when left clicking village DHD with iron pickaxe

### ISSUE THREAD

**Issue by brisingraerowing** [AlmuraDev/SGCraft#173]
I was holding an iron pickaxe and accidentally left clicked on a DHD that generated in the village I was in, and immediately crashed.

[Crash Log](https://gist.github.com/BrisingrAerowing/977883eb11c8c2b53f6476a9f6b7ae11)

This might be caused by one of the other mods I have (FoamFix and VanillaFix are likely culprits, as they mess with rendering stuff).

Also, what level pickaxe is required to mine a DHD? TOP always shows that they are not harvestable, even when holding a Diamond pickaxe.

**Comment by bsixel** [comment]
I encountered this same bug - the culprit in my case was VanillaFix. I'm sure you've since figured something out, but in case you haven't, I had to disable the textureFixes portion of VanillaFix, unfortunately.

**Comment by Dockter** [comment]
I can't even look at the line in TextureMap that caused the NPE because your client is using something to inject nearly 1,000 lines of code into it.
