### ISSUE TITLE
[Issue][Config] dimensionIDs is missing from the documentation. What does it do?

### ISSUE THREAD

**Issue by dustojnikhummer** [AlmuraDev/SGCraft#174]
dimensionIDs=0 is the default config in Naquadah{} section, but its explanation is missing in your documentation. 

Is there a way to get Naquadah to generate in Aroma Mining World?

**Comment by Bottswana** [comment]
Based on the code in NaquadahOreWorldGen.java, I believe it is a comma delimited string.
For me, Aroma1997's Mining world dim is -6. so I used a value of 0,-6

**Comment by dustojnikhummer** [comment]
So the line would be dimensionIDs=0,dimensionID1,dimensionID2 and so on?

**Comment by Bottswana** [comment]
Exactly

**Comment by dustojnikhummer** [comment]
Thanks!
