### ISSUE TITLE
atlantis iris 

### ISSUE THREAD

**Issue by 0NDINEK** [AlmuraDev/SGCraft#178]
hi I wanted to ask if theres any day when the atlantis city shield is coming to this mod ;)

**Comment by frozenLake** [comment]
While the Shield on the Gate and the City Shield are two seperate things, I would also love an alternative shield that activates faster than the OG Iris, just like how the Atlantis Gates dial faster than the Milky Way gates.

**Comment by 0NDINEK** [comment]
Iam sorry lol I was meaning the atlantis gate shield like alteran iris :) sorry for that :D

**Comment by Dockter** [comment]
I would love to add a feature like this unfortunately I am not good with rendering code.  The rendering class is so far beyond my knowledge I don't even know where to start.
