### ISSUE TITLE
[Suggestion] Subscribable Forge event on gate creation

### ISSUE THREAD

**Issue by bsixel** [AlmuraDev/SGCraft#179]
Post a custom Forge event to the EVENT_BUS when a gate is merged (SGBaseTE: 834). This would allow for addons that react to gate creation and removal. If the event contained the gate's address and whether the gate was merged vs un-merged we could build addons that spawned mobs from the gate's position, add the address to loot elsewhere, etc.
Not sure about your PR policy - I could probably do this if you're currently accepting PRs.

**Comment by Dockter** [comment]
I would accept a PR for this.  I'm about to start working on this again.

**Comment by Dockter** [comment]
Oh, I see you did a PR, I will review.

**Comment by Dockter** [comment]
This was pulled.  Thanks for taking the time to do this.  Sorry it took me nearly a year to get around to this.
