### ISSUE TITLE
sg speed does not set for Pegasus gate

### ISSUE THREAD

**Issue by iceyrazor** [AlmuraDev/SGCraft#182]
this is a simple one that i dont think requires alot of info. the config D:ringRotationSpeed=10.0 only sets for the normal stargate. not the Pegasus stargate. atleast in my testing it does. 

if you need me to show you i can do a short video of both dialing with a timer

**Comment by Dockter** [comment]
The pegasus gate dial speed is hard-set at 6.0 when its created.  You can change this using the configurator.
