### ISSUE TITLE
no zpm hub 

### ISSUE THREAD

**Issue by Sparcky-Snowtail** [AlmuraDev/SGCraft#186]
no zpm hub

**Comment by Lloydplays** [comment]
no zpm hub

**Comment by ghost** [comment]
Same here.
Edit: Do i need some extra mods like malisis for pdd?

**Comment by DartisXUI** [comment]
malasiscore for the hand held devices (pdd, gdo & maybe configurator)
IC2 for zpm cart, zpm hub
opencomputers for oc interface
cc:tweaked for cc interface

**Comment by Dockter** [comment]
I assume that since the original person who filed this ticket didn't include any actual usable information that this was a case of missing a mod.
