### ISSUE TITLE
Stargates aren't mineable.

### ISSUE THREAD

**Issue by Bantoo1231** [AlmuraDev/SGCraft#187]
I've set the config to true but the stargates I find out in the wild can't be mined and when testing in creative the core block can't be mind regardless if it's generated by the world or placed by me

**Comment by Dockter** [comment]
I've completely changed how I handle this function.  There are two new options coming
- B:canPlayerBreakGeneratedGate=false
- B:canPlayerBreakPlayerGate=true

This should be self explanatory.  

A generated gate is set multiple ways; which I'll outline soon.
