### ISSUE TITLE
Client Crash with Better Foliage Rendering?  v2.0.5

### ISSUE THREAD

**Issue by Cephelo** [AlmuraDev/SGCraft#188]
Unsure as to what exactly caused this crash, but something strange happened with rendering a water block.  This happened once upon joining the world, and continues to happen every time I join that world.
[crash-2022-04-18_00.51.50-client.txt](https://github.com/AlmuraDev/SGCraft/files/8503812/crash-2022-04-18_00.51.50-client.txt)
.

**Comment by Dockter** [comment]
Is there anything else special about water?  I've looked at that code and I don't see anything standing out that would cause this.

**Comment by Cephelo** [comment]
This may just be a small incompatibility with better foliage then, as I've never seen this crash before this report. I reported this to the Better Foliage guys, so let's see what happens.  I guess in the meantime keep this issue open.
Issue was posted at: octarine-noise/BetterFoliage#430

**Comment by Cephelo** [comment]
Upon further examination, I believe this was just an additional crash that happened with the attached one - I think this is a non-issue.
[crash-2022-04-18_00.51.47-server.txt](https://github.com/AlmuraDev/SGCraft/files/9126987/crash-2022-04-18_00.51.47-server.txt)
