### ISSUE TITLE
Crash when opening RF Stargate Power Unit

### ISSUE THREAD

**Issue by drzpk** [AlmuraDev/SGCraft#19]
Game crashes when I try to open RF Stargate Power Unit (right click).

Crash log:
[crash-2018-08-09_14.19.30-client.txt](https://github.com/AlmuraDev/SGCraft/files/2274116/crash-2018-08-09_14.19.30-client.txt)

**Comment by Dockter** [comment]
Fixed.  You can find download here: https://ore.spongepowered.org/Dockter/SGCraft
