### ISSUE TITLE
Inter-dimensional travel is impossible

### ISSUE THREAD

**Issue by drzpk** [AlmuraDev/SGCraft#22]
When I try to travel from overworld to nether, after entering an address and pressing enter Stargate starts dialing sequence and immediately shuts down. I was able to determine that chunk unload event causes this issue (defined in `SGCraft.onChunkUnload`), but I only got this far because I'm not really good at wormhole physics. :(

**Comment by Dockter** [comment]
I have seen this issue as well though I thought it had something to do with Sponge.  Are you using Sponge and what version of the mod are you using?

**Comment by drzpk** [comment]
I have spotted this issue in `1.15.2-forge-release`, but I've just made a test on [db380f](https://github.com/AlmuraDev/SGCraft/commit/db380f7136f96e8ee9f1fba4562de9337de87e16) - the same issue occurs.

**Comment by Dockter** [comment]
Right but you didn't answer whether or not you were using sponge.

**Comment by drzpk** [comment]
If you're referring to [THIS](https://www.spongepowered.org/), then no, I'm not using it.

**Comment by Dockter** [comment]
See, now this is helpful, now I can quit chasing my tail with Sponge.  I will work on this shortly.

**Comment by drzpk** [comment]
Sorry, I wasn't aware what Sponge was exactly (thought it was a separate platform).

**Comment by Dockter** [comment]
Found and fixed the issue.  I will be pushing a fix to this to forge/api-7 versions.

**Comment by Dockter** [comment]
Fixed, and posted here: https://ore.spongepowered.org/Dockter/SGCraft/pages/Home
