### ISSUE TITLE
[Enhancement ] Stargate Transport Rings

### ISSUE THREAD

**Issue by Tsoccerguy3** [AlmuraDev/SGCraft#24]
I have seen this done with command blocks , it would be a great addition to add in the model and code
![images](https://user-images.githubusercontent.com/22108822/44178634-3f8ae680-a0c1-11e8-8d17-aef66bb72282.jpg)

http://stargate.wikia.com/wiki/Transportation_rings

Video Animation
https://www.youtube.com/watch?v=iXAuXd-PSB8

**Comment by Tsoccerguy3** [comment]
Almost a year and no artist to tackle the challenge , hope someone stumbles by this and is kind enough to make a model .:)

**Comment by BDevGW** [comment]
Would love to se transport rings to directly move upwards / downwards.

**Comment by Dockter** [comment]
I don't foresee this happening, I lack the knowledge to implement this.
