### ISSUE TITLE
Bug when riding through a stargate

### ISSUE THREAD

**Issue by MatWein** [AlmuraDev/SGCraft#28]
If the player is riding an entity (for example a horse) and travels through a stargate that has at least 100 blocks of distance to the other stargate, the entity is not correctly spawned at the other side and the player freezes within the gate (see screenshot). In that state the player can't move or do anything else. After restarting the game, the entity is spawned correctly.

Nearby gates work fine. Only gates with bigger distance seem to have this problem.

![screenshot](https://user-images.githubusercontent.com/35470253/44366022-a5191180-a4cb-11e8-9700-88b24e47f271.png)

I'm using vanilla minecraft with the only mod:
- SGCraft-1.15.5-forge-release.jar

**Comment by Dockter** [comment]
Well then..... Thats actually impressive.  I'll investigate.  Did it matter WHAT you were riding?

**Comment by MatWein** [comment]
I don't think that the kind of entity matters. I tried with an horse and a (custom) Puddle Jumper entity. At least they both didn't work.

**Comment by TherayTharow** [comment]
But Minecarts work fine with me in them

**Comment by MatWein** [comment]
If you want you can reproduce this bug using my private server:
https://drive.google.com/drive/folders/0B0j8KrUZmc4ER0JJVy1tVXdZY0E?usp=sharing

Also the following bug is reproducable in this world: 
https://github.com/AlmuraDev/SGCraft/issues/26

The stargate can be dialed by using the following script on the computer:
/home/stargate/dial.lua
There are also saved all dialable adresses.

**Comment by Dockter** [comment]
I intend to start working on this this weekend.  I am planning on re-writing the entire teleport method.  The way Greg did things is out of date.

**Comment by Dockter** [comment]
I have fixed this as of 1.20.3
