### ISSUE TITLE
[Feature Request] Please add your SGCraft to CurseForge

### ISSUE THREAD

**Issue by sandalle** [AlmuraDev/SGCraft#37]
As a request from a modpack maintainer, please add the Forge version (the other versions are unlikely to work in CurseForge managed modpacks due to the SpongeForge dependency) of your SGCraft to CurseForge . :) You'll need a different name than "SGCraft" as it's already taken by the original author in https://minecraft.curseforge.com/projects/sg-craft  (e.g. the renamed fork https://minecraft.curseforge.com/projects/un-official-port-of-sg-craft ).

**Comment by liach** [comment]
@dockter fyi you can profit from downloads on curseforge

**Comment by Dockter** [comment]
The fact that SGCraft is taken and they won't let me post it under the original name even though I have Gregs permissions is the very reason why I won't be putting it on curse.

**Comment by sandalle** [comment]
If you have permission, Greg is supposed to set you up as an author on https://minecraft.curseforge.com/projects/sg-craft so that you can continue the mod (a la https://minecraft.curseforge.com/projects/roots) and can set himself as Former Author if he wants.

**Comment by Dockter** [comment]
The problem is he hasn't been around in years.  I got permissions from him a long time ago and curse doesn't care. I've played Curses' games for years and I am not about to start that up again.

**Comment by sandalle** [comment]
Sorry to hear that it's been difficult dealing with Curse. I haven't always had the best experience either, but overall it's been a great platform. What's the issue with just calling it "SGCraft Renewed" (or similar) and link to Greg's permission to continue the mod?

Alternatively, can you get 3rd party permission (https://authors.curseforge.com/knowledge-base/minecraft/120-minecraft-modpack-submission links to https://docs.google.com/spreadsheets/d/1lEwbJpwRVoZb8kr0OT-Wo4Yc7jAGWMGOFtfL0miCFmc/edit#gid=0 , which links to https://goo.gl/67orWF ) for requesting https://ore.spongepowered.org/Dockter/SGCraft be a third-party approved mod (a la GalactiCraft and others), as I don't see it listed. :)
