### ISSUE TITLE
Errors with GDO

### ISSUE THREAD

**Issue by Stegorix** [AlmuraDev/SGCraft#38]
When dialing the DHD with a GDO in the off-hand, with each character errors get thrown in the console. The client crashes when I try to delete an already dialed char. The Bug consists over all tested Forge and Sponge versions (2705, 2768, 2772). 
Attached are the logs from Forge 2705 and 2772. First I dialed a random adress without GDO. After that the same with the Item in the off-hand. Also tested with a dedicated Server.

[latest2705.log](https://github.com/AlmuraDev/SGCraft/files/2570079/latest2705.log)
[latest2771.log](https://github.com/AlmuraDev/SGCraft/files/2570080/latest2771.log)

**Comment by Stegorix** [comment]
After some experimenting I got the Item to work, but only combined with your almura-mod. 
So the minimal modlist seems to be:

Forge 2768

almura-mc[1.12.2]-forge[2768]-sf[RC3497]-b60.jar
industrialcraft-2-2.8.101-ex112.jar
malisiscore-1.12.2-6.4.2-SNAPSHOT.jar
SGCraft-1.15.6-SF-new-features-release.jar
spongeforge-1.12.2-2768-7.1.3-RC3498.jar

**Comment by Dockter** [comment]
Issue has been found.  I'll work on fixing this in the next day or so.

https://github.com/AlmuraDev/SGCraft/blob/feature/zpm/src/mod/gcewing/sg/DHDTE.java#L78

Contamination of access transformers from previous Forge projects.

**Comment by liach** [comment]
You can simply use `getItem()` instead for that field reference.

**Comment by Dockter** [comment]
Fixed in build of 1.15.7-SF-new-features-release.
