### ISSUE TITLE
Integration with BungeeCord?

### ISSUE THREAD

**Issue by ianc1215** [AlmuraDev/SGCraft#39]
I am not sure how feasible this would be but I really would like to see a way for SGCraft to be integrated with BungeeCord so you could have a true multiverse feel to Minecraft. Is this a possible feature/plugin that could be added in later versions?

**Comment by Dockter** [comment]
This would be extremely complicated because the modpacks running SGCraft would need to be exact or the client connection would fail.  Therefore this isn't a priority at the moment.
