### ISSUE TITLE
Any planned Updates? Also Curse Forge?

### ISSUE THREAD

**Issue by StoneLegion** [AlmuraDev/SGCraft#41]
I think we are allowed to Distro on Curse but I wanted to check first if it was something you wanted to do before we did it. As well as were you considering fixing anything else I noticed a few issues it sounded like you wanted to fix them a couple months ago but did not get to it.

If we post on Curse can we just link directly here?

**Comment by Dockter** [comment]
I have renamed the project I had started to "Stargate Network" to get around curse's bullshit naming rights rules.  https://minecraft.curseforge.com/projects/stargate-network
