### ISSUE TITLE
Mixin and forge version conflicts and NoClassDefFoundError crash

### ISSUE THREAD

**Issue by Mitchell5200** [AlmuraDev/SGCraft#43]
Modpack: Atm3-remix v1.0.2  (yes i'm crazy)
SGCraft file version 1.15.6-SF-new-features-release
as mentioned on discord as user "Mitchell52"

logs are from the serverlauncher files 
https://pastebin.com/tt2dUspE  with malisis core and doors disabled and no spongeforge  --forge version mismatch
https://pastebin.com/u3bHma45 with malisis core and doors enabled and no spongeforge  --mixin version mismatch

after correctly enabling sponge it crashes upon world load with a NoClassDefFoundError
https://pastebin.com/6SzPT5ba with 1.15.6-SF-new-features-release and spongeforge

**Comment by Dockter** [comment]
This has to do with the version of Malisis you're using.  Search ore.spongepowered.org, you'll find what you need there.  I posted a newer version that fixes this exact issue.
