### ISSUE TITLE
Crash with latest build on Curse with mixins. 

### ISSUE THREAD

**Issue by StoneLegion** [AlmuraDev/SGCraft#45]
https://pastebin.com/RsEGZ1Na
SGCraft-1.20.0.jar

Crashes before actually loading.

**Comment by Dockter** [comment]
What else are you using that utilizes mixin?

**Comment by StoneLegion** [comment]
Besides your mod it seems nothing else. I tried to search the log for MixinBootstrap without anything coming up and tried Mixin and still nothing without your new version or the sponge version you had before.

This on pure forge no sponge of course.

**Comment by Dockter** [comment]
That's impossible because your error indicates that you have something already loading mixin, which is an earlier version that 0.7.11.

**Comment by liach** [comment]
@KaneHart Give a full log instead.

**Comment by StoneLegion** [comment]
https://pastebin.com/jBVNAAvq
Sorry about that this the full log.

**Comment by liach** [comment]
```
[18:53:30] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.4 Source=file:/C:/Users/kanec/Documents/Curse/Minecraft/Instances/The%20Next%20Leap/mods/malisiscore-1.12.2-6.4.0.jar Service=LaunchWrapper Env=CLIENT
```
Hehe, malisiscore! That's it.

**Comment by Dockter** [comment]
Use this build of Malisis to solve your issue.

https://ore.spongepowered.org/Dockter/MalisisCore

**Comment by liach** [comment]
Uh, that build does not exist on curseforge unfortunately.

**Comment by Dockter** [comment]
So what, download it anyways.

**Comment by StoneLegion** [comment]
You must not know the new terms but Curse does not allow that anymore. The only way you can use a repeated mod like that is to publish on curse then add the original mod author to it with permissions sadly. 

Either way it's the other mods at fault ish and both for anything sponge haha.
