### ISSUE TITLE
I have a number of suggestions and questions

### ISSUE THREAD

**Issue by KiraLinux** [AlmuraDev/SGCraft#46]
Remove addiction mode IC2.
objects do not move through the gate, they disappear

the gate must kill the player when he tries to go back, you cannot enter the gate that has an incoming call (in the series, the gate is one-sided, send a call from them and go over there),
Now the gates do not kill the player when he tries to go back

the gate must kill the player in everything that he is equipped with
(this is the law of the gate from the series in the original as it is)

mod version SGCraft-1.20.0

**Comment by Dockter** [comment]
1. IC2 dependency (required) has been removed.  
2. I have considered doing that honestly (killing the player), sounds like a good feature to work on...

**Comment by Dockter** [comment]
I added this feature.  It will appear in version 1.20.3.

Thanks.

**Comment by KiraLinux** [comment]
Thanks
