### ISSUE TITLE
SGCraft: DHD Sounds Don't Obey Config File Sound Setting 

### ISSUE THREAD

**Issue by dubbeanh** [AlmuraDev/SGCraft#48]
In the config file, last section, I set the following option:
D:soundVolume=0.4

This has led to a drastic volume reduction (as intended) for stargate operations. It however does not affect the dialing sounds from the DHD.

Intended?

Link to previous post:
https://github.com/AlmuraDev/GameServer/issues/38

**Comment by Dockter** [comment]
Fixed in 2.0.0-alpha 2 or greater.
