### ISSUE TITLE
RF Stargate Power Unit not accepting RF Power from any RF Source

### ISSUE THREAD

**Issue by Quisquid** [AlmuraDev/SGCraft#50]
I tried to Power a Stargate with RF via RF Stargate Power Unit with a Creative Energy Cell connected. But there is no RF transferred from the Energy Cell to the RF Stargate Power Unit. I tried some other RF Sources i had available but nothing worked. 

MC: 1.12.2
Forge: 1.12.2-14.23.5.2768
SGCraft: 1.20.3
ThermalExpansion: 5.5.3.41
Thermal Foundation 2.6.2.26
Thermal Dynamics: 2.5.4.18
CofhCore: 4.6.2.25

**Comment by Dockter** [comment]
I've known of this issue for a bit but haven't taken the time to setup a perfect testing environment to fix it.  I'll put this on my to-do list for this weekend.

**Comment by Dockter** [comment]
This is on hold at the moment because of CoFH's stupidity.  How many damn sub mods do you seriously need.  All of the deobf jar's are on old mappings.  Like usual all of their stuff is months and months behind current code.

**Comment by Quisquid** [comment]
Do you mean the standalone „Redstone Flux“ mod when you talk about the damn sub mods?

I hope there will be a solution in the future. Thanks for trying to fix the issue!

**Comment by Quisquid** [comment]
Have you taken a look on ForgeEnergy yet?
Micro Infinity (µI) from EnderIO is basically ForgeEnergy and since 1.11 every mod which produces RF also produces FE to my knowledge.
Implementing a Stargate FE Interface maybe solves the issue once and for all?

Maybe this doesn't work. 
Neither I am an Minecraft mod expert nor a programmer. Its just an idea from my point of view as an user.

**Comment by Dockter** [comment]
This should be work in the next version.  FYI, the RF Power unit is gone, replaced with SG Power Unit.
