### ISSUE TITLE
Stargates only operate in one direction

### ISSUE THREAD

**Issue by ianc1215** [AlmuraDev/SGCraft#52]
I was messing around with SGCraft 1.20.3 and noticed that once I dial a gate (both have DHDs) I am only able to travel through the gate in one direction but not back through the same connection until I redial the other side from the gate I just was sent to. I looked through the config and did not see anything that mentioned "one-way travel". Is this a bug or a feature?

**Comment by Quisquid** [comment]
I have no problem to disable one-way-travel in the config file. Just set the option "B:oneWayTravel=true" in the "stargate" node to "false" and restart your game/server.

In the series it is not possible to travel backwards through an opened wormhole. That is the reason for this option.

This is the part of the config file highlighted:

**stargate** {
    D:bufferSize=2500.0
    B:closeFromEitherEnd=true
    D:distanceFactorMultiplier=1.0
    D:energyPerFuelItem=96000.0
    B:explosionFlame=true
    I:explosionRadius=10
    B:explosionSmoke=true
    I:gateOpeningsPerFuelItem=24
    D:interDimensionMultiplier=4.0
    D:maxEnergyBuffer=1000.0
    I:minutesOpenPerFuelItem=80
    **B:oneWayTravel=true**
    B:reverseWormholeKills=false
    I:secondsToStayOpen=300
    D:soundVolume=1.0
    B:transparency=true
    B:variableChevronPositions=true
}

**Comment by Dockter** [comment]
The above information is correct AT THE MOMENT, as the next update will give each gate the ability to be set independent of the global configs.
