### ISSUE TITLE
Todo list prior to full SGCraft 2.0.0 release

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/SGCraft#53]
The following is what I have left to do before I prepare to release build 2.0.0

- Add language entries

**Comment by AlexM-Dev** [comment]
Will the Tollan Phase shifting device allow for walking through walls too, or would that be too far?

**Comment by Dockter** [comment]
The only way I can do that is to essentially imitate spectator mode, which personally I don't want to do at this point.

**Comment by PowellA12** [comment]
could have it tap them in and out of spectator mode?

**Comment by Dockter** [comment]
Not my goal.

**Comment by PowellA12** [comment]
okay
