### ISSUE TITLE
2.0.0 - release notes

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/SGCraft#54]
The following is a breakdown of the features / changes within SGCraft 2.0.0

**New Features**
##### **PDD, GDO and Configurator features require MalisisCore or MalisisEgo dependency**
Download Here:  http://solder.almuramc.com/downloads/malisiscore-1.12.2-6.5.1.jar
- Added GDO to give users control of their local and remote stargate iris controllers
- Added PDD which allows users to store Stargate addresses into a single handheld device.  This feature will also allow server admin's to pre-program common addresses into it.
- Added Configurator device which allows server admins or players access to new unique configuration options per Stargate
- Added SG Power Block (replaced RF Power Block).  Uses built-in Forge power systems.
- Added "Preserve Iris State" which will return the Iris to the state it was prior to dialing Stargate on wormhole disconnect.
- Added "No Input Power Required", requires no power to dial destinations.
- Made the feature "Transient Damage" (when wormhole opens) configurable.
- Added "Chevrons lock when dialed" where when the DHD is used will lock each chevron as its dialed vs watching the ring rotation dial sequence.  This feature works slightly different when used in combination with the PDD.
- Added permissions system which relies on SpongeAPI, feature is optional, not required.
- Added dependency on MalisisCore or (EGO) for PDD, Configurator and GDO devices.  Feature is optional, not required unless you want to use PDD, Configurator and GDO.
- Added "Accept Incoming Connections", which will prevent someone from dialing that specific Stargate
- Added Horizontal based Stargates. 
- Added Tollan Phase-shifting device which allows an admin to pass-thru any Iris. (Creative Item Only)
- Added Gate Address control system
- Added Player Access control system.
- Blocked access to DHD fuel screen unless player has Admin access to connected stargate.
- Moved ZPM to a non-exclusive feature.  ZPM Interface Cart will remain for IC2.
- Added ZPM Console
- Added new Pegasus dialing sounds
- Added the ability to link a DHD outside of its normal range.  Sneak-Right-Click the base of a Stargate then Sneak-Right-Click the DHD.  You will see messages regarding saved location and created link.
- Added random/configurable Stargate generations within all Temple types. (Igloo, Jungle, Pyramid, Swamp Hut)

**PDD Functionality**
- Users can add/remove/edit their own list of Stargate addresses as well as set a readable name for each entry and an index number for which they appear in the PDD list.
- Server owners can pre-populate the PDD device with common addresses which the users can or cannot delete/edit.
- To use PDD, put the device in your hand and right-click it while near a Stargate, the GUI will open automatically.
- The PDD addresses are stored in NBT and are unique to each item.  This means you can copy and share the items using various methods.
- PDD will allow user to select the gate address from the list and click "Dial Selected Address"  and the Stargate will automatically dial the address while showing a connection progress.  The GUI will also show and error state if issues were encountered during dialing as well as allow the user to disconnect the gates wormhole.
- PDD entry can be added by either pressing the + button in the GUI OR by sneaking and then right-clicking the PDD handheld while you are near a Stargate, the "Add PDD Entry" window will automatically appear.
- PDD can be used near the base of the Stargate or the linked DHD.

**GDO Functionality**
- GDO will allow a user to open/close both a local and a remote based Iris.  The GDO also allows the user to disconnect a wormhole.
- GDO (may) have the ability to read from a list of players saved using the Configurator device which allows access to open the iris.  Otherwise at the moment it is based on the players ability to modify the Stargates base block itself.
- GDO shows the current state of each gate so you can see visually what the state of the iris is on the other end of the wormhole.
- GDO can be used near the base of the Stargate or the linked DHD.

**Configurator Options**
1. Seconds To Stay Open
2. Gate Rotation Speed
3. Energy Buffer Size
4. Energy Per Naquadah
5. Openings Per Naquadah
6. Distance Factor Multiplier
7. Inter-Dimensional Dimension Multiplier
8. One-Way Travel Only
9. Iris Upgrade
10. Chevron Upgrade
11. Pegasus Gate Design Type
12. Preverse Wormhole Kills
13. Accept Incoming Connections
14. Close from Either End
15. Preserve Inventory on Iris Death
16. No Input Power Required
17. Chevrons lock when dialed
18. Return to Previous Iris State
19. Enable Transient Damage
20. Enabled Event Horizon Transparency

- Note: Configurator can be used to link long distance DHD's to a Stargate.  Sneak-right-click the base of the Stargate with a Configurator and then sneak-right-click a DHD to create a link.

**Gate Address Control System**
- Allows admins to set which addresses are allowed or disallowed from dialing IN or OUT
- Allows admins to set a default value to allowing incoming or outgoing wormholes

**Player Access Control System**
- Allows admins to set players ability to use stargate for both incoming and outgoing
- Allows admins to set players ability to control iris controller
- Allows admins to set whether or not a player can modify the base configuration of a Stargate

**Fixed  Issues**
1. Fixed issue where DHD wouldn't detect a Stargate connection properly.
2. Fixed player velocity when exiting Stargate. 
3. Fixed issue with RedstoneFlux / ThermalExpansion Power block.
4. Fixed sync/desync issue between client and server's NBT data.
5. Fixed an issue where the Stargates Iris Entity was being tracked for Teleport.
6. Fixed how the Base block camo/inventory window appears.  If the player doesn't have admin access to the stargate then the non-inventory GUI window will appear with only the gate address 
shown.
7. Camo slots are hidden when using horizontal based Stargates.
8. Fixed DHD press button sounds not respecting global sound volume values.
9. Fixed SG based blocks dropping in the event of an explosion even if canHarvest was false.
10. Fixed snow accumulating on Stargate, DHD & Power Units.
11. Fixed CI interface not sending "incoming"/"outgoing" during dialing procedure.
12. Fixed an "unknown" state being sent to CI interfaces during connection phase.
13. Fixed missing event horizon sound.

**Removed**
1. Removed the RFPower Block, it was replaced with the SG Power Block.

**Comment by Dockter** [comment]
Update:
**Features Added**
- Added Gate Address control system
- Added Player Access control system.

**Gate Address Control System**
- Allows admins to set which addresses are allowed or disallowed from dialing IN or OUT
- Allows admins to set a default value to allowing incoming or outgoing wormholes

**Player Access Control System**
- Allows admins to set players ability to use stargate for both incoming and outgoing
- Allows admins to set players ability to control iris controller
- Allows admins to set whether or not a player can modify the base configuration of a Stargate

**Comment by Dockter** [comment]
I've also decided to change this build to SGCraft version 2.0.  I've changed / added thousands of lines of code at this point.

**Comment by PowellA12** [comment]
sounds good!
