### ISSUE TITLE
Supergates

### ISSUE THREAD

**Issue by AllyMarthaJ** [AlmuraDev/SGCraft#55]
Hey,

Would it be possible to implement some form of Supergate?

Obviously it would require a massive amount more power (could potentially limit supergates to being dialled with an immense power source, such as a possible black hole). 

Maybe they wouldn't be diallable using a DHD (something else much bigger, perhaps).

Thanks.

**Comment by Dockter** [comment]
This is complicated.  The model format "smeg" was something greg wrote up by hand I believe.  I can't simply exchange his model format with OBJ.  I would say this is on the radar but not a priority until the model issue can be resolved.

**Comment by Brendan-H** [comment]
Please add it!
