### ISSUE TITLE
Dialinvvg is not a world

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/SGCraft#57]
![2019-03-13_17 20 21](https://user-images.githubusercontent.com/39970604/54315531-c00cb980-45b4-11e9-8d10-7737c4165143.png)

**Comment by TherayTharow** [comment]
only happens on the flat ones maybe

**Comment by Dockter** [comment]
I already have fixed this, code just not on the repo yet.

**Comment by TherayTharow** [comment]
oh k
