### ISSUE TITLE
Please remove IC2 requirement for ZPMs

### ISSUE THREAD

**Issue by ZyorTaelon** [AlmuraDev/SGCraft#59]
There are a lot of modpacks out there that have dropped or not included IC2 for various valid reasons.
Would it be possible to enable ZPMs to still work even if IC2 isn't present?

**Comment by Dockter** [comment]
How about a variation?  

The ZPM itself isn't unique to IC2, the ZPM interface cart is.  I could make a "ancient platform" to accept the ZPM that uses the same power system as the SG Power Unit.  Therefore the concept of how I have the zpm implemented wouldn't need to change much...

**Comment by ZyorTaelon** [comment]
That sounds like a great idea @Dockter !
Were you thinking of something like [this](https://vignette.wikia.nocookie.net/stargate/images/2/23/BeforeISleep11.jpg/revision/latest?cb=20111015210250)? (It's from  the main ZPM room of Atlantis)

**Comment by Dockter** [comment]
That was my original idea yes, getting my wife to make the model, that's a different story.

**Comment by ZyorTaelon** [comment]
Perhaps if you tell her she'll get lots of <3 from Stargate & Minecraft fans from all over the world? :)

**Comment by Dockter** [comment]
The work on this has begun.  I am not happy with my first implementation of the ZPM Console itself.  I will continue to work on this.

**Comment by Dockter** [comment]
This has been completed, 2.0.0 - alpha 12+.
