### ISSUE TITLE
dial(address) broken for OpenComputers in 2.0.0

### ISSUE THREAD

**Issue by Nex4rius** [AlmuraDev/SGCraft#60]
This code should work but it doesn't.
<img src="https://oc.cil.li/uploads/monthly_2019_03/asd.PNG.07026c6e696e286a53afda58a8ea3a38.PNG">

**Comment by Dockter** [comment]
Try this please:  http://solder.almuramc.com/downloads/SGCraft-2.0.0-alpha-8.jar

**Comment by Nex4rius** [comment]
It kinda works... but if you call that function again the dialling gets interrupted and the other gate cannot be dialed anymore and you get "targetbusy" even thought its clearly not busy.

**Comment by Dockter** [comment]
Hello,  can you ping me in discord please.  I need a bunch more information on how you created this and what happens in specific steps.

**Comment by Dockter** [comment]
Fixed in alpha 13+.
