### ISSUE TITLE
[Enhancement] Return Initiator during dialing sequence

### ISSUE THREAD

**Issue by STiGYFishh** [AlmuraDev/SGCraft#61]
Currently the direction of travel returns an empty string during the dialing process. e.g. state, engaged, direction

`Dialing 6 `
`Opening 7 `
`Connected 7 Incoming`

I've not looked at the codebase in great deal, but if it's not too hard, it would be a nice QoL to be able to determine direction of travel during the dialing sequence to pre-emptively close the iris etc..

**Comment by Dockter** [comment]
I can resolve this.

**Comment by STiGYFishh** [comment]
> 
> 
> I can resolve this.

Awesome cheers. However I've managed to hack it.
for some reason, if a conenction is incoming the state progresses:
`IDLE -> UNKNOWN -> DIALLING`
and when a connection is outgoing
`IDLE -> DIALLING`

the "Unknown" state only ever appears between idle and dialling for an incoming connection. If this helps at all.

**Comment by Dockter** [comment]
One thing I want to be known though is if I start "fixing" some of these dialing issues with the CC interfaces then its possible a change may be required in your program.

**Comment by Dockter** [comment]
I need to see the code that you're using that generates the "Dialing 6", "Opening 7"  please.

**Comment by Dockter** [comment]
Fixed in alpha 15.
