### ISSUE TITLE
Dialing Gate in unloaded chunks

### ISSUE THREAD

**Issue by Sarous** [AlmuraDev/SGCraft#62]
2.0.0 (alpha) version

Cannot dial a Stargate whose chunk is not currently loaded. Dials normally if the recieving chunk is loaded, otherwise returns "no address" error as if no gate exists at the address. Repeatable.

**Comment by Dockter** [comment]
Check your testing environment, none of that code has been touched.

**Comment by Sarous** [comment]
Retested on a clean world with only sgcraft/maliscore and worked correctly, both 1.20 and 2.0.0 a25. Will spend some time mix n matching mods to see if I can figure out the conflict.
