### ISSUE TITLE
ZPM Console is missing it's name and recipe

### ISSUE THREAD

**Issue by ZyorTaelon** [AlmuraDev/SGCraft#64]
We're running SGCraft-2.0.0-alpha-26 and the ZPM Console is missing it's name and it doesn't have a recipe.
![image](https://user-images.githubusercontent.com/1486566/54944341-90a26900-4f33-11e9-8c5a-bd2354f159c4.png)

**Comment by Dockter** [comment]
I know.  Not finished yet :)

**Comment by ZyorTaelon** [comment]
Woops. I'm sorry! I didn't mean to come over as impatient... I saw you closed #59 so I was afraid the ZPM console was ready for testing and bug reports.. :)

**Comment by Dockter** [comment]
No if anything this serves as a reminder to fix this before I do a beta version.

**Comment by Dockter** [comment]
Completed.
