### ISSUE TITLE
Auto-Dialer handheld device

### ISSUE THREAD

**Issue by Dockter** [AlmuraDev/SGCraft#7]
Idea, implement an auto-dialer handheld device to store stargate addresses.

This would allow users the ability to travel to gates without having to remember the address.

**Comment by ZyorTaelon** [comment]
There's a computercraft program that can also be run on the handheld device.
http://www.computercraft.info/forums2/index.php?/topic/16656-lanteacraft-sgcraft-ccdhd/

**Comment by Dockter** [comment]
That would require the Compucraft mod which I dont want to implement at this time.

**Comment by ZyorTaelon** [comment]
There's no need to implement anything. It's already compiled even. Just add the jar to your mods folder and tada... handheld dialer.

**Comment by Dockter** [comment]
Exactly, the Almura server wont be using Compucraft.

**Comment by ZyorTaelon** [comment]
Open Computers has a similar dialing program.

The thing is. The Stargates were intended to be dialed by DHD. If you watch the movie and tv show you'll notice the SGC had to connect unrelated computers to the stargate in order to dial it without a DHD. Same goes for this mod :)

**Comment by Dockter** [comment]
Work on this module has begun.

**Comment by Dockter** [comment]
I have a working prototype for this, its awesome.

**Comment by Quisquid** [comment]
I am curious about it! 
But is it possible to disable it in the config for someone who is using Computercraft/OpenComputers on his server? Like me? gg

**Comment by Dockter** [comment]
Yes, very much so.  I am also introducing a "Admin Configurator Tool" that will allow you to configure every single option of a unique stargate.  No longer will the gates have a global config that controls all of them.  They will inherit the global config option is either they are a new gate or its requested they inherit them.  Otherwise you'll be able to configure everything.  You would be surprised all the configuration options that exist per stargate that currently are not configurable in the base configs.  That is going to change.

**Comment by TherayTharow** [comment]
woot woot woot will you be able to set the address for the stargate?

**Comment by Dockter** [comment]
No, you will not be able to set the address.  That is a mathematical computation that is used to assign all gate addresses.  Changing that system would destroy the gate system as we know it.

**Comment by TherayTharow** [comment]
k do you have the mathematical computation in equation form?
not in java script form 
-i have tried reading the files involved i have not understood how it gets the address it does

**Comment by Dockter** [comment]
This feature has been implemented.
