### ISSUE TITLE
build.gradle needs a update

### ISSUE THREAD

**Issue by Tsoccerguy3** [AlmuraDev/SGCraft#70]
Dok , It would be a great idea to fix build.gradle so that it downloads all the dependencies and installs them in the local maven , instead of looking for them to put in the lib directory. It saves time looking for them . 

Thank you

C:\Users\ASUS\Dev\sgc>gradlew build

> Configure project :
This mapping 'snapshot_20180808' was designed for MC 1.12! Use at your own peril.
Found AccessTransformer: oc_at.cfg_OpenComputers-MC1.12.2-1.7.2.67_at.cfg

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find deobf.dan200.computercraft:ComputerCraft:1.80pr1-build4.
     Searched in the following locations:
         https://files.minecraftforge.net/maven/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.pom
         https://files.minecraftforge.net/maven/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.jar
         https://repo.maven.apache.org/maven2/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.pom
         https://repo.maven.apache.org/maven2/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.jar
         https://libraries.minecraft.net/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.pom
         https://libraries.minecraft.net/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.jar
         http://files.minecraftforge.net/maven/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.pom
         http://files.minecraftforge.net/maven/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.jar
         http://maven.cil.li/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.pom
         http://maven.cil.li/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.jar
         https://oss.sonatype.org/content/groups/public/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.pom
         https://oss.sonatype.org/content/groups/public/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.jar
         http://maven.ic2.player.to/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.pom
         http://maven.ic2.player.to/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.jar
         http://repo.spongepowered.org/maven/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.pom
         http://repo.spongepowered.org/maven/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.jar
         http://cc.crzd.me/maven/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.pom
         http://cc.crzd.me/maven/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.jar
         file:/C:/Users/ASUS/.gradle/caches/minecraft/deobfedDeps/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.pom
         file:/C:/Users/ASUS/.gradle/caches/minecraft/deobfedDeps/deobf/dan200/computercraft/ComputerCraft/1.80pr1-build4/ComputerCraft-1.80pr1-build4.jar
         file:/C:/Users/ASUS/Dev/sgc/.gradle/minecraft/ComputerCraft-1.80pr1-build4.jar
         file:/C:/Users/ASUS/Dev/sgc/.gradle/minecraft/ComputerCraft.jar
     Required by:
         project :
   > Could not find deobf.com.almuradev:malisiscore:1.12.2-6.5.0-SNAPSHOT.
     Searched in the following locations:
         https://files.minecraftforge.net/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/maven-metadata.xml
         https://files.minecraftforge.net/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.pom
         https://files.minecraftforge.net/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         https://repo.maven.apache.org/maven2/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/maven-metadata.xml
         https://repo.maven.apache.org/maven2/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.pom
         https://repo.maven.apache.org/maven2/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         https://libraries.minecraft.net/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/maven-metadata.xml
         https://libraries.minecraft.net/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.pom
         https://libraries.minecraft.net/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         http://files.minecraftforge.net/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/maven-metadata.xml
         http://files.minecraftforge.net/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.pom
         http://files.minecraftforge.net/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         http://maven.cil.li/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/maven-metadata.xml
         http://maven.cil.li/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.pom
         http://maven.cil.li/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         https://oss.sonatype.org/content/groups/public/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/maven-metadata.xml
         https://oss.sonatype.org/content/groups/public/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.pom
         https://oss.sonatype.org/content/groups/public/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         http://maven.ic2.player.to/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/maven-metadata.xml
         http://maven.ic2.player.to/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.pom
         http://maven.ic2.player.to/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         http://repo.spongepowered.org/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/maven-metadata.xml
         http://repo.spongepowered.org/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.pom
         http://repo.spongepowered.org/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         http://cc.crzd.me/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/maven-metadata.xml
         http://cc.crzd.me/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.pom
         http://cc.crzd.me/maven/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         file:/C:/Users/ASUS/.gradle/caches/minecraft/deobfedDeps/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/maven-metadata.xml
         file:/C:/Users/ASUS/.gradle/caches/minecraft/deobfedDeps/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.pom
         file:/C:/Users/ASUS/.gradle/caches/minecraft/deobfedDeps/deobf/com/almuradev/malisiscore/1.12.2-6.5.0-SNAPSHOT/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         file:/C:/Users/ASUS/Dev/sgc/.gradle/minecraft/malisiscore-1.12.2-6.5.0-SNAPSHOT.jar
         file:/C:/Users/ASUS/Dev/sgc/.gradle/minecraft/malisiscore.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by Dockter** [comment]
Fixed.
