### ISSUE TITLE
Chevron Locking sound either doesn't obey sound config, or its significantly louder than all other sounds.

### ISSUE THREAD

**Issue by dubbeanh** [AlmuraDev/SGCraft#73]
I've gradually reduced the SGcraft sound config down to 0.2 with no discernable difference between the chevron locking sound.

I will freely admit I am partially deaf and use bone conducting amplification, It can be difficult for me to tell the difference in minute changes.

That being said, either the sound played on chevron lock (both gate styles) either has the base volume much louder than all the other sounds, or it is not obeying the sound config setting.

**Comment by Dockter** [comment]
I need to know which version you're running.

**Comment by dubbeanh** [comment]
2.0.0 Beta 2

**Comment by Dockter** [comment]
When you change the volume in the config are you restarting the game completely?  This setting does NOT hot load.

**Comment by BBtraceur** [comment]
srry to pry on a closed issue, but it's not fixed yet. I was about to make a new issue when I saw this one. 
I play on SGCraft-2.0.0-beta-4. 
description: When dialing (both gate type 1 & 2) the turning (spooling) sound (when going to the right glyph) of the gate is very loud. Editing the sound in config DOES do something but it only lowers the sound from everything else; chevron locking (both dialing and incoming), event horizon gate establishment, idle & disconection and stepping through an active gate. I think that is all the sounds I heard =p

I just checked to be sure, addition to the loud unaltered sound is the DHD button pushing.

This happends on a server client (yes I rebooted) and client side (also full shutdown, even the launcher).

If you need any aditional info, I'm happy to help.

Just wanted to add that I'm happy someone picked up this mod. I'm a returning player trying to set up a private server (for friends) and I just can't play without a stargate =) thx for the trouble!

**Comment by dubbeanh** [comment]
Heh.
