### ISSUE TITLE
Crash when trying to disable naquadah ores.

### ISSUE THREAD

**Issue by ProsperCraft** [AlmuraDev/SGCraft#74]
naquadah {
    B:debugLava=false
    I:debugLevel=0
    B:debugRandom=false
    I:genIsolatedOdds=0
    I:genUnderLavaOdds=0
    I:maxIsolatedNodes=0
    I:maxNodesUnderLava=0
}

Leads to https://gist.github.com/ProsperCraft/e9aa692ffc60af4049e666fe7fe0ec0f

**Comment by Dockter** [comment]
Well then....
I need to fix that.

**Comment by Dockter** [comment]
Actually, you're doing this wrong.

options {
    B:enableNaquadahOre=true
}

You disabled the wrong thing.
