### ISSUE TITLE
Cannot dial stargate + error in server console

### ISSUE THREAD

**Issue by nicolas-stein** [AlmuraDev/SGCraft#75]
Hi, I'm having an issue with the mod.
I've placed a stargate in the end dimension and I can't dial to it. (but still able to dial from it).
Everytime I enter the address, nothing happens in game (no messages in chat saying wrong address or gate dialing) but I can see an error in the server console. I'm running a SpongeForge server (forge version : forge-1.12.2-14.23.5.2768-universal and sponge version : spongeforge-1.12.2-2768-7.1.5), and I'm using sgcraft 2.0.0-beta-2 and malisiscore-1.12.2-6.5.1 (I'm _not_ using IC2).

(Also i'm using a plugin to generate other dimensions like the overworld and the stargate works well)

Error in the console : https://gist.github.com/nicoloconicolas/f16298f7b6fbc93a8d95495e50d829d4

**Comment by Dockter** [comment]
Please put this stack trace in a gist.github.com so it can be read...

**Comment by nicolas-stein** [comment]
Okay sorry I'm not very familiar with github, I've edited the original message with the link now.

**Comment by Dockter** [comment]
Fixed in beta 4.
