### ISSUE TITLE
Stargate Power issue 2.0.0-Beta-4

### ISSUE THREAD

**Issue by SpadesSlick1** [AlmuraDev/SGCraft#77]
The Stargate is registering the blocks and can activate using the power in them however the power isn't then drained from the block itself.

Edit: I was slightly wrong. It does drain the power as long as the SG Power Units aren't connected to a source of power. However even when completely drained (16Mil RF) It automatically refilled then all without taking away from my reserves at all.

**Comment by navaroneee** [comment]
I can confirm, it does not expend energy if it is connected to a power source, if it removes it starts to spend, but does not spend the source itself

**Comment by Dockter** [comment]
Please use 2.0.1 and report back any issues.

Thanks,
