### ISSUE TITLE
Stargate Chevron Upgrade 2.0.0-Beta-4

### ISSUE THREAD

**Issue by SpadesSlick1** [AlmuraDev/SGCraft#78]
When you add a chevron upgrade it isn't removed from your inventory and when you destroy the stargate you get the upgrade back giving you a second one. I just did this to make sure it wasn't lag and I've gotten 3 upgrades from it.

**Comment by Sarous** [comment]
Just tested in survival, and it correctly takes my chevron item during upgrade. HOWEVER, if I am in Create Mode, mine acts as you are describing. Returning the upgrade on block destruction has always been so, and I assume to be a feature, not a bug?

**Comment by Dockter** [comment]
This is working as intended if you're in creative mode.  If you use the configurator then this is also expected.
