### ISSUE TITLE
BUG unable to remove recipe with crafttweaker

### ISSUE THREAD

**Issue by collwee** [AlmuraDev/SGCraft#8]
i can remove recipe from other mods with crafttweaker without problem but with sg craft the recipe cannot be removed 

forge 14.23.2.2613
crafttweaker2-1.12-4.1.5
SGCraft-1.14.3-mc1.12.2

would it by possible to fix or at-least make possible to disable the default recipe to make possible the creation of custom recipe

**Comment by Dockter** [comment]
Should be able to do this actually.  Recipe is done in code right now and not json.

**Comment by liach** [comment]
report to crafttweaker instead.

**Comment by Dockter** [comment]
@Liach why?

**Comment by liach** [comment]
in theory it modifies the registry; thus it can remove hardcoded recipes.

**Comment by jaredlll08** [comment]
Yea @liach is right, ***in theory*** it can remove hardcoded recipes, provided you register them before postinit... 

https://github.com/AlmuraDev/SGCraft/blob/1.12.2/src/base/gcewing/sg/BaseMod.java#L207

Honestly, JSON is better for me, since I then know when they are being registered.

**Comment by Dockter** [comment]
Fixed and pushed here.  Each recipe can now be disabled via config.
https://ore.spongepowered.org/Dockter/SGCraft/pages/Home

**Comment by Dockter** [comment]
I also moved the registration to init so if you really want to use crafttweaker to remove them you can.
