### ISSUE TITLE
Gate Address Access List not working

### ISSUE THREAD

**Issue by Sarous** [AlmuraDev/SGCraft#81]
SGCraft 2.0.0 beta4
Malisiscore 6.5.1
Forge 1.12.2-14.23.5.2814

Gate Address Access List (GAAL) cannot change Default Outgoing permissions at all. Changing the checkbox does not save state after hitting save; reverts to "allow" when next accessed via configurator.

GAAL saves changes to Default Incoming permission, but has no effect. Gates set to default deny incoming can still be dialed. Likewise, a gate set to default deny can dial a receiving gate set to default deny.

edit: typo

Edit: More testing results:
Setting default to allow incoming/outgoing; setting specific gate to deny incomning
Gate correctly prevents reception (only case of success)

Any setting which involves Default-Deny fails.

Hypothesis:
When the Default is set to allow, the specific gate checks for denials run, and are set corrently.
When the Default is set to Deny, it does not perform specific gate checks for denials, as they would be the same setting as the current default.
Therefore, suspecting the bug lie in the default denial line itself, and could probably just be re-copied from the specific gate checks (as they are currently working).

**Comment by Dockter** [comment]
OK after some basic debugging I've found that this is a multiple bug issue.

1st bug is the GUI isn't updating correctly due to a typo when reading from NBT on the client, easy fix.
2nd bug is how I handle default assumptions about allowing outgoing, allowing incoming.  This is taking slightly more time....

**Comment by Dockter** [comment]
I'm fairly certain I fixed this in 2.0.0, the full release.  Can you try that and let me know?

**Comment by Sarous** [comment]
Seems to be fully working

**Comment by Dockter** [comment]
Excellent. Thanks for re-testing.
