### ISSUE TITLE
Overlaping sounds

### ISSUE THREAD

**Issue by Sarous** [AlmuraDev/SGCraft#86]
Beta 6
a host of other mods including Twilight Forest 3.9.888

When a Stargate is dialing (pegasus soundset, have not tested milky way) and a Twilight Forest bird chirps, the Stargate's sounds abruptly go silent for the duration of the bird chirp.

Uncertain if this is a mod conflict bug or native, as I have no way to test it without mods.

**Comment by Dockter** [comment]
I believe, quote unquote, that this is within Mojangs sound system.
