### ISSUE TITLE
Trying to connect to a new world

### ISSUE THREAD

**Issue by Cleardragonf** [AlmuraDev/SGCraft#89]
Gates have connected but won't allow players to move between worlds...sound works...but player nor item ever leaves

**Comment by Dockter** [comment]
Please check to make sure you're not having a permissions issue if you use one.  Also, a list of mods and logs is helpful.

**Comment by Cleardragonf** [comment]
does SGcraft require a permission to use the stargates? cause when i create portals using project portal I have no issues... going from point a to point b...

**Comment by Cleardragonf** [comment]
here's a [link](https://www.dropbox.com/s/r3z9lpn0ykbey4s/ModPack.zip?dl=0) to the mods in my modpack being used.

**Comment by Cleardragonf** [comment]
[Log File](https://www.dropbox.com/s/22ufsuwja2s4a64/2019-06-01-1.log.gz?dl=0)

apparantly it is throwing an error message when i try to cross through.

**Comment by Dockter** [comment]
OK, so lets backup.

You're using SpongeForge, which would enable the permissions checks.  Are you using LuckyPerms too?

**Comment by Dockter** [comment]
No response from user.
