### ISSUE TITLE
Crash in dedicated server

### ISSUE THREAD

**Issue by NAPPUS** [AlmuraDev/SGCraft#9]
I have put the 1.12.2 version in server and i got this crash report, any way to solve this? This crash happen when you close the stargate from the DHD or when the time for the gate to stay opened end.. thanks in advance
https://pastebin.com/8Uw7p0SH

**Comment by Dockter** [comment]
I need an entire server mod list.

Thanks,

**Comment by NAPPUS** [comment]
Here the mod list, thanks for your help, is really appreciated!
![image_9](https://user-images.githubusercontent.com/23039852/37392434-764b3408-276e-11e8-88a8-9e6987963604.png)

**Comment by Dockter** [comment]
Something seems to be changing that method name via ASM or something.  It makes no sense that world wouldn't exist plus SGCraft isn't anywhere in that stack trace.

**Comment by Dockter** [comment]
Let me know when you can get me a more complete log file.  I haven't been able to reproduce this at all in the latest versions available here: https://ore.spongepowered.org/Dockter/SGCraft
