### ISSUE TITLE
Suggestion: Some Sort of Dimension Based Items to Upgrade the Gates.

### ISSUE THREAD

**Issue by StoneLegion** [AlmuraDev/SGCraft#91]
I would love some sort of special support if it's via the DHD or Gate some sort of support that would allow you to travel to other dimensions being able to lock progression behind new types of items.

From my understanding now you have just the standard gate and then the upgrade to another dim. But it would be nice if we could use an item even via config, etc where we can set or create our own item say via content tweaker to be able to block the end access till you install a new type of item.

This would give a lot of customization on more progression based packs and be quite a lot of fun. 

Thanks :)

**Comment by craft90** [comment]
Doesn't DimStages do this? It can lock dimensions and have an item as "key" at least.

**Comment by Dockter** [comment]
You can already do this via permissions with SpongeForge.

**Comment by StoneLegion** [comment]
Sponge Forge is never a solution ever lol. This is quite old I personally not as Interested in it's need or support not sure if @electrobot needs it.

**Comment by Dockter** [comment]
@KaneHart that's ignorance speaking.  That comment alone should disqualify this conversation.

**Comment by StoneLegion** [comment]
Just because I refuse to use Sponge Forge to break 30 other mods does not mean I'm being ignorant. Thinking that people should use it as a requirement for features is where your being the ignorant one. 

I like that you maintained and updated SG but I'm not personally going to use Sponge Forge as a solution to create more problems nor am I going chase down and have them all fixed up... Maybe in the days when Blood himself fix them in 10 seconds but those days are done.

**Comment by Dockter** [comment]
Likely if its breaking 30 other mods then you're likely using mods that do custom ASM bullshit or modifying shit off thread.

That being said, I'm not offering to help someone who bashes a product that they know nothing about.

**Comment by StoneLegion** [comment]
So I don't know that the reason mods don't work with Sponge Forge is not because of Sponge Forge but like you said custom ASM crap that is not using the correct hooks, etc. Causes a lot of random issues and it's 100% the mods fault and not sponge forge?

So Yeah I do know that and I also know that trying have all these devs fix their code is like pulling teeth I tried for the longest time. I personally don't run servers like I once did needing to do big permission / protection systems.

So I guess having a feature in a Mod suggest using something as large as Sponge Forge I feel is maybe the term bloatish for our needs lol. 

Either way it's fine the request is reject I respect that but respect the reasons we don't use Sponge Forge and don't expect to drop a big chunk of mods and think I have no clue what I'm talking about.

It's like someone who runs Linux Only setup saying Linux or GTFO. Principle wise I respect but sadly 95% of games are windows only... Fix that and I'm there in a heart beat.
