### ISSUE TITLE
Lightning strike on active gate

### ISSUE THREAD

**Issue by BBtraceur** [AlmuraDev/SGCraft#92]
The Lightning striked the base block of the gate while it just established connection. It made the server crash immediately.

https://pastebin.com/82KQEZK2

What are the odds right? :p

-BBTraceur

**Comment by Dockter** [comment]
This is an oversight on my part.  I will fix ASAP.

**Comment by BBtraceur** [comment]
np, thx for the support

**Comment by Dockter** [comment]
Fixed in 2.0.1

**Comment by Nex4rius** [comment]
Just a weird idea but what if the gate just activates and connects to a random address when hit by lightning?
