### ISSUE TITLE
CCL error with Greg tech and SGCraft

### ISSUE THREAD

**Issue by Blazer4Hire** [AlmuraDev/SGCraft#93]
I was using your mod in a pack of mine but for some reson, I get:

 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-19, y:62, z:271
  Block Class:   class gregtech.common.blocks.surfacerock.BlockSurfaceRockFlooded
  Registry Name: gregtech:surface_rock_flooded_0
  Metadata:      7
  State:         gregtech:surface_rock_flooded_0[level=0,material=iron]
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null

(This happens with all Greg tech nuggets that spawn underwater, not just iron)

I only ever get this error with SGCraft and Greg tech installed. I did find the issue on their Greg tech's GitHub but it was thought to be another mods issue. While testing the old way by uninstalling and reinstalling mods I found that I only get this issue with SGCraft. I coincidentally found that other people who got the same error also had SGCcraft and Greg tech installed. I don't want to sound like I'm pointing fingers, but I was wondering if it is possible that SGCraft could be having issues with Greg techs nuggets that are placed into the world that sometimes wind up underwater?

**Comment by Dockter** [comment]
I need a full stack trace.  SGCraft is no where in the above information provided.  Please advise.

**Comment by Blazer4Hire** [comment]
[latest.log](https://github.com/AlmuraDev/SGCraft/files/3249279/latest.log)

**Comment by Blazer4Hire** [comment]
It is a very long log. The Greg tech errors are near the bottom.

**Comment by Blazer4Hire** [comment]
also over time, the errored nuggets in the water disappear and they cause "an air block" around itself except for the water doesn't render as if it were air.
![2019-06-03_16 02 23](https://user-images.githubusercontent.com/50091501/58831571-f9d0e780-861a-11e9-955e-5a7a86aebcc2.png)

**Comment by Dockter** [comment]
Honestly I can't see SGCraft anywhere in any of the exceptions logging.  Its possible some of greg ewings rendering code overlaps with other greg tech mods on the class loader though that would be terrible if that was the case.  Honestly don't have a suggestion for you on this.
