### ISSUE TITLE
Wormhole destroys unbreakable blocks

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [AlmuraDev/SGCraft#97]
Transient phase of wormhole should not be able to destroy unbreakable blocks such as bedrock and reinforced blocks from securitycraft.

**Comment by FatherSarge** [comment]
Should be toggleable on the config if it isn't already

**Comment by C4PTRAMPAGE** [comment]
i want it to damage players and destroy blocks, just not unbreakable ones...

**Comment by FatherSarge** [comment]
Ah gotcha. Maybe there needs to be a new config to be able to turn on/off the ability to destroy indestructible blocks. I'd love to use them to punch a hole through bedrock 😂

**Comment by C4PTRAMPAGE** [comment]
another thing is that since it can break those blocks it makes securitycraft pointless, my base isn't 100% secure anymore. i don't like that.

**Comment by Dockter** [comment]
Hm....  I agree with you @C4PTRAMPAGE , I will investigate a change to the code and make this configurable.

**Comment by Dockter** [comment]
Added this feature / ability to version 2.0.2
